### ISSUE TITLE
Add support for "Ё"

### ISSUE THREAD

**Issue by veronikazaglotova** [Miodec/monkey-type#278]
Although it's becoming more and more rare, there's a letter Ё in Russian language which some people do use. For example, me. It's frustrating when you see a word that is typed with Ё correctly and the program tells you that it isn't right and that you have to change it to Е. Pls fix.

A common fix is to make Ё and E interchangeable, that way everyone will be happy.

**Comment by Miodec** [comment]
Is that letter not recognised at all? How are you typing it? Would replacing all occurrences of that letter with e's work as a solution?

**Comment by zezic** [comment]
The thing is that some text sources found on both web and real life are using the `Е` letter as a simplification over the `Ё` letter. This can be caused by many reasons (some of them are technical and some are historical ones). But when someone reads a word with such `Ё` letter replaced by `Е`, then he/she will automatically speak that word inside his/her head as it was written with the proper `Ё` glyph.

For example, when I read the `лед` (which is for `ice` in English) I automatically pronounce it as `лёд` inside my head which leads to intention to write the `ё` letter instead of `е`.

So the solution for this can be to accept both `ё` and `е` letters typed from keyboard if there is `е` letter found in text.

**Comment by Miodec** [comment]
Alright - Ill make it so ё and е are interchangeable.
