### ISSUE TITLE
Add support for PT-BR

### ISSUE THREAD

**Issue by guilhermedeandrade** [Miodec/monkey-type#29]
I would like to help on adding support for Brazilian Portuguese. However, I took a look at the code and it seems that I'd need access to Firebase, right? Please, let me know if I can help!

**Comment by Miodec** [comment]
As far as i can tell when developing locally firebase just starts a node server, so you could try that. (I will get do some research and set up a general “how to collaborate” guide some time soon)

But since adding languages is super simple, you could do it without even having to set up a local server. Just add another key to the words object in words.js file. Everything else should work

**Comment by guilhermedeandrade** [comment]
Oh, ok! I will do it and open a PR then! Thanks for the info @Miodec 🙌

**Comment by guilhermedeandrade** [comment]
Tried to run the project locally but I wasn't able to, could be you provide some info about the setup?

**Comment by Miodec** [comment]
Okay so from what i learned if you want to run this project locally fully working with a database and stuff you need to create a new project on firebase on your google account, and then change the project name in `.firebaserc`. Make sure you [install the firebase CLI](https://firebase.google.com/docs/cli#install_the_firebase_cli) and then `firebase serve --only hosting` to start a server. Let me know if you run into any issues

**Comment by guilhermedeandrade** [comment]
Ok, I will try this ASAP! Thanks!

**Comment by Miodec** [comment]
34d081898e19ae0483da6d5f5b1cb4174127387f
