### ISSUE TITLE
Is Steno allowed?

### ISSUE THREAD

**Issue by aericktoes** [Miodec/monkey-type#339]
I created an account, but none of my scores are being saved because it has detected me as a possible bot. Is there any way I can get around this? Or is steno just not allowed at all?

**Comment by Miodec** [comment]
As i mentioned on discord, the software that is parsing all the chords is probably sending all the keycodes with a length of 1ms and all at the same time -  which is being picked up by the bot detection (most likely because of the 1ms key duration) since that is the most basic and easiest way of detecting a macro/bot (there are other steps in place). 

Sorry about that, but if I wanted to support steno i would have to drop the bot detection entirely.

**Comment by aericktoes** [comment]
That's understandable. Thanks for clarifying.
