### ISSUE TITLE
Make the favicon change according to the selected theme

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkey-type#38]

**Comment by artophe** [comment]
Hi Miodec, 

Since the favicon change according to the selected theme new feature, the monkey-type favicon seems to appear in full black when saved as a Firefox bookmarks. Same issue with all themes.

Many thanks for your great site !

![favicon](https://user-images.githubusercontent.com/7824666/82564403-fe1e4980-9b78-11ea-823a-6ea65f1d4444.jpg)

**Comment by Miodec** [comment]
Firefox causing issues once more haha - thanks, looking into it.

**Comment by Miodec** [comment]
@artophe Did you try removing the bookmark and adding it again? For some reason im not experiencing this issue (im assuming you are also using the latest version)

![Screenshot 2020-05-21 at 16 32 39](https://user-images.githubusercontent.com/13181393/82575807-d9c66b00-9b80-11ea-9cc4-942b4c095980.png)

**Comment by artophe** [comment]
Yep ! I'm using Firefox 76.0.1 on Windows 10 (2004).

I've tried to remove the bookmark multiple times : same issue unfortunately.
I've also tried to switch to Firefox default light theme.

**Comment by Miodec** [comment]
Okay, should be fixed in 80fc3d237358c99a7e3a1ac87a16192e74381f08. I tried to make it pull the colors from the theme, but one solution worked in Firefox but not Chrome and the other worked the other way - so i just settled for resetting to default.
