### ISSUE TITLE
Losing typing records

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkey-type#400]
I haven't found a way to stably reproduce this, but recently I found if I restart the test quickly using keyboard shortcut on the account page, there's a chance the following test result won't be saved properly. I've lost several records already if I push through tests back to back. Now I have to super patient and wait extra time to ensure the results get properly recorded.

**Comment by Miodec** [comment]
As far as i know you dont need to wait for results to be saved since  that is done asynchronously. Maybe there is a problem with adding results to the local copy of your results, but I would need a way to reproduce this to really investigate. Also, next time you notice a test missing from the account page, try refreshing to see if it pops up. Maybe that will help us find an issue you are experiencing.

**Comment by pingshunhuangalex** [comment]
Thanks for the reply. I did try to refresh or even continue with another test, but the data never shows up that's why I'm certain it's missing. Will post more details here if I find anything else. Thanks.

**Comment by pingshunhuangalex** [comment]
Found the reason. The record is still there, but somehow my tag dropped since yesterday so it's never showing up cuz I have specific filter on.

Not sure why the tag suddenly dropped tho, but I'll close this issue cuz the description is no longer accurate.
