### ISSUE TITLE
add pause functionality for test

### ISSUE THREAD

**Issue by rolfvreijdenberger** [Miodec/monkey-type#402]
Hi! 

An idea I'd like to pitch would be to introduce a pause functionality during a test. 

A specific use case I run into is that when doing a custom test with a lot of words (book typing practice) I sometimes get interrupted by things that pop up. Instead of stopping and restarting the test later, I'd like to be able to pause the test and resume when I'm ready.

This keeps me honest during my practice :)

Just like 'esc' and 'tab' are hotkeys during the test, another hotkey could be introduced, or a tab+tab+enter could be used to trigger the pause.

I'd like to take some time to dive into the code later this month for adding a custom wordlist and will try to familiarize myself a bit. If any pointers are put here, I might be able to contribute.

**Comment by Miodec** [comment]
It was suggested a couple of times before and the general idea was that it can mess up some of the Discord challenges + how the afk time is supposed to be calculated then and so on. So probably wont be added for now, sorry.

**Comment by Kelvets** [comment]
I don't give a damn about challenges with other people, my times are for personal use only. Why do I have to be punished not having a pause function because other people cheat on challenges I won't even be a part of?

Perhaps the solution would be making so that if the pause function is used, this is made very clear at the results screen, which would invalidate those results for challenge purposes. But please, add a pause function! I'm tired of my long typing tests being ruined because something unexpected came up and I had to stop the test, or losing WPM because I had to stop to scratch my back, etc.

**Comment by realmwright** [comment]
he's got a point
